name: CICD
on:
  push

env:
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: "Setup python"
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - run: pip install poetry
      - run: poetry run pip install lightfm
      - run: make setup
      - run: make lint
      - run: make test
